load:
  type: constant
  rate: 1
  duration: 30
vllm:
  model_name: HuggingFaceTB/SmolLM2-135M-Instruct
  url: http://0.0.0.0:8000
metrics:
  server_type: prometheus
  prometheus_server_config:
    url: http://0.0.0.0:9091
    scrape_interval: 15
